language: rust

rust:
  - nightly

install:
  - travis_retry curl -Lf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.3/mdbook-v0.2.3-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/.cargo/bin

script:
  - export PATH=$PATH:/home/travis/.cargo/bin && mdbook test
  - cd stable-check && cargo run -- ../src
