[book]

title = "The Rust Reference"
author = "The Rust Project Developers"

[output.html]
additional-css = ["theme/reference.css"]
git-repository-url = "https://github.com/rust-lang-nursery/reference/"
