[book]
title = "The Rust Reference Developer Guide"
language = "en"

[output.html]
git-repository-url = "https://github.com/rust-lang/reference/tree/master/dev-guide"
edit-url-template = "https://github.com/rust-lang/reference/edit/master/dev-guide/{path}"
smart-punctuation = true

[output.html.search]
use-boolean-and = true
